import { ReactComponent as Activity } from './activity.svg';
import { ReactComponent as Airplay } from './airplay.svg';
import { ReactComponent as AlertCircle } from './alert-circle.svg';
import { ReactComponent as AlertOctagon } from './alert-octagon.svg';
import { ReactComponent as AlertTriangle } from './alert-triangle.svg';
import { ReactComponent as AlignCenter } from './align-center.svg';
import { ReactComponent as AlignJustify } from './align-justify.svg';
import { ReactComponent as AlignLeft } from './align-left.svg';
import { ReactComponent as AlignRight } from './align-right.svg';
import { ReactComponent as Anchor } from './anchor.svg';
import { ReactComponent as Aperture } from './aperture.svg';
import { ReactComponent as Archive } from './archive.svg';
import { ReactComponent as Arrow } from './arrow-down-circle.svg';
import { ReactComponent as ArrowDownLeft } from './arrow-down-left.svg';
import { ReactComponent as ArrowDownRight } from './arrow-down-right.svg';
import { ReactComponent as ArrowDown } from './arrow-down.svg';
import { ReactComponent as ArrowLeftCircle } from './arrow-left-circle.svg';
import { ReactComponent as ArrowLeft } from './arrow-left.svg';
import { ReactComponent as ArrowRightCircle } from './arrow-right-circle.svg';
import { ReactComponent as ArrowRight } from './arrow-right.svg';
import { ReactComponent as ArrowUpCircle } from './arrow-up-circle.svg';
import { ReactComponent as ArrowUp } from './arrow-up.svg';
import { ReactComponent as ArrowUpLeft } from './arrow-up-left.svg';
import { ReactComponent as ArrowUpRight } from './arrow-up-right.svg';
import { ReactComponent as At } from './at-sign.svg';
import { ReactComponent as Award } from './award.svg';
import { ReactComponent as BarChar } from './bar-chart-2.svg';
import { ReactComponent as Bar } from './bar-chart.svg';
import { ReactComponent as Battery } from './battery.svg';
import { ReactComponent as BatteryCharging } from './battery-charging.svg';
import { ReactComponent as BellOff } from './bell-off.svg';
import { ReactComponent as Bell } from './bell.svg';
import { ReactComponent as Bluetooth } from './bluetooth.svg';
import { ReactComponent as Bold } from './bold.svg';
import { ReactComponent as BookOpen } from './book-open.svg';
import { ReactComponent as Book } from './book.svg';
import { ReactComponent as Bookmark } from './bookmark.svg';
import { ReactComponent as Box } from './box.svg';
import { ReactComponent as Briefcase } from './briefcase.svg';
import { ReactComponent as Calendar } from './calendar.svg';
import { ReactComponent as CameraOff } from './camera-off.svg';
import { ReactComponent as Camera } from './camera.svg';
import { ReactComponent as Cast } from './cast.svg';
import { ReactComponent as CheckCircle } from './check-circle.svg';
import { ReactComponent as CheckSquare } from './check-square.svg';
import { ReactComponent as Check } from './check.svg';
import { ReactComponent as ChevronDown } from './chevron-down.svg';
import { ReactComponent as ChevronLeft } from './chevron-left.svg';
import { ReactComponent as ChevronRight } from './chevron-right.svg';
import { ReactComponent as ChevronUp } from './chevron-up.svg';
import { ReactComponent as Chrome } from './chrome.svg';
import { ReactComponent as ChevronsDown } from './chevrons-down.svg';
import { ReactComponent as ChevronsLeft } from './chevrons-left.svg';
import { ReactComponent as ChevronsRight } from './chevrons-right.svg';
import { ReactComponent as ChevronsUp } from './chevrons-up.svg';
import { ReactComponent as Circle } from './circle.svg';
import { ReactComponent as Clipboard } from './clipboard.svg';
import { ReactComponent as Clock } from './clock.svg';
import { ReactComponent as CloudDrizzle } from './cloud-drizzle.svg';
import { ReactComponent as CloudLightning } from './cloud-lightning.svg';
import { ReactComponent as CloudOff } from './cloud-off.svg';
import { ReactComponent as CloudRain } from './cloud-rain.svg';
import { ReactComponent as CloudSnow } from './cloud-snow.svg';
import { ReactComponent as Cloud } from './cloud.svg';
import { ReactComponent as Code } from './code.svg';
import { ReactComponent as Codepen } from './codepen.svg';
import { ReactComponent as Codesandbox } from './codesandbox.svg';
import { ReactComponent as Coffee } from './coffee.svg';
import { ReactComponent as Columns } from './columns.svg';
import { ReactComponent as Command } from './command.svg';
import { ReactComponent as Compass } from './compass.svg';
import { ReactComponent as Copy } from './copy.svg';
import { ReactComponent as CornerDownLeft } from './corner-down-left.svg';
import { ReactComponent as CornerDownRight } from './corner-down-right.svg';
import { ReactComponent as CornerLeftDown } from './corner-left-down.svg';
import { ReactComponent as CornerRightDown } from './corner-right-down.svg';
import { ReactComponent as CornerLeftUp } from './corner-left-up.svg';
import { ReactComponent as CornerRightUp } from './corner-right-up.svg';
import { ReactComponent as CornerUpLeft } from './corner-up-left.svg';
import { ReactComponent as CornerUpRight } from './corner-up-right.svg';
import { ReactComponent as Cpu } from './cpu.svg';
import { ReactComponent as CreditCard } from './credit-card.svg';
import { ReactComponent as Crop } from './crop.svg';
import { ReactComponent as Crosshair } from './crosshair.svg';
import { ReactComponent as DeleteSVG } from './delete.svg';
import { ReactComponent as Dollar } from './dollar-sign.svg';
import { ReactComponent as Watch } from './watch.svg';
import { ReactComponent as WifiOff } from './wifi-off.svg';
import { ReactComponent as Wifi } from './wifi.svg';
import { ReactComponent as Wind } from './wind.svg';
import { ReactComponent as Edit2 } from './edit-2.svg';
import { ReactComponent as Edit3 } from './edit-3.svg';
import { ReactComponent as Edit } from './edit.svg';
import { ReactComponent as External } from './external-link.svg';
import { ReactComponent as EyeOff } from './eye-off.svg';
import { ReactComponent as Eye } from './eye.svg';
import { ReactComponent as Radio } from './radio.svg';
import { ReactComponent as Receipt } from './receipt-outline 2.svg';
import { ReactComponent as RefreshCcw } from './refresh-ccw.svg';
import { ReactComponent as RefreshCw } from './refresh-cw.svg';
import { ReactComponent as Repeat } from './repeat.svg';
import { ReactComponent as Rewind } from './rewind.svg';
import { ReactComponent as RotateCcw } from './rotate-ccw.svg';
import { ReactComponent as RotateCw } from './rotate-cw.svg';
import { ReactComponent as Rss } from './rss.svg';
import { ReactComponent as Table } from './table.svg';
import { ReactComponent as Tablet } from './tablet.svg';
import { ReactComponent as Tag } from './tag.svg';
import { ReactComponent as Target } from './target.svg';
import { ReactComponent as Terminal } from './terminal.svg';
import { ReactComponent as Thermometer } from './thermometer.svg';
import { ReactComponent as ThumbsDown } from './thumbs-down.svg';
import { ReactComponent as ThumbsUp } from './thumbs-up.svg';
import { ReactComponent as ToggleLeft } from './toggle-left.svg';
import { ReactComponent as ToggleRight } from './toggle-right.svg';
import { ReactComponent as Tool } from './tool.svg';
import { ReactComponent as Trash2 } from './trash-2.svg';
import { ReactComponent as Trash } from './trash.svg';
import { ReactComponent as Trello } from './trello.svg';
import { ReactComponent as TrendingDown } from './trending-down.svg';
import { ReactComponent as TrendingUp } from './trending-up.svg';
import { ReactComponent as Triangle } from './triangle.svg';
import { ReactComponent as Truck } from './truck.svg';
import { ReactComponent as Tv } from './tv.svg';
import { ReactComponent as Twitch } from './twitch.svg';
import { ReactComponent as Twitter } from './twitter.svg';
import { ReactComponent as TypeSVG } from './type.svg';
import { ReactComponent as Youtube } from './youtube.svg';
import { ReactComponent as Umbrella } from './umbrella.svg';
import { ReactComponent as Underline } from './underline.svg';
import { ReactComponent as Unlock } from './unlock.svg';
import { ReactComponent as Upload } from './upload.svg';
import { ReactComponent as User } from './user.svg';
import { ReactComponent as Image } from './image.svg';
import { ReactComponent as Inbox } from './inbox.svg';
import { ReactComponent as Info } from './info.svg';
import { ReactComponent as Instagram } from './instagram.svg';
import { ReactComponent as Italic } from './italic.svg';
import { ReactComponent as Octagon } from './octagon.svg';
import { ReactComponent as Layers } from './layers.svg';
import { ReactComponent as Layout } from './layout.svg';
import { ReactComponent as Life } from './life-buoy.svg';
import { ReactComponent as Link } from './link.svg';
import { ReactComponent as Linkedin } from './linkedin.svg';
import { ReactComponent as List } from './list.svg';
import { ReactComponent as Loader } from './loader.svg';
import { ReactComponent as Lock } from './lock.svg';
import { ReactComponent as LogIn } from './log-in.svg';
import { ReactComponent as LogOut } from './log-out.svg';
import { ReactComponent as Key } from './key.svg';
import { ReactComponent as Hard } from './hard-drive.svg';
import { ReactComponent as Hash } from './hash.svg';
import { ReactComponent as Heart } from './heart.svg';
import { ReactComponent as Headphones } from './headphones.svg';
import { ReactComponent as Help } from './help-circle.svg';
import { ReactComponent as Hexagon } from './hexagon.svg';
import { ReactComponent as Home } from './home.svg';
import { ReactComponent as Gift } from './gift.svg';
import { ReactComponent as Git } from './git-commit.svg';
import { ReactComponent as Github } from './github.svg';
import { ReactComponent as Gitlab } from './gitlab.svg';
import { ReactComponent as Globe } from './globe.svg';
import { ReactComponent as Grid } from './grid.svg';
import { ReactComponent as Facebook } from './facebook.svg';
import { ReactComponent as Fast } from './fast-forward.svg';
import { ReactComponent as Feather } from './feather.svg';
import { ReactComponent as Figma } from './figma.svg';
import { ReactComponent as File } from './file.svg';
import { ReactComponent as Film } from './film.svg';
import { ReactComponent as Filter } from './filter.svg';
import { ReactComponent as Flag } from './flag.svg';
import { ReactComponent as Folder } from './folder.svg';
import { ReactComponent as Framer } from './framer.svg';
import { ReactComponent as Frown } from './frown.svg';
import { ReactComponent as Database } from './database.svg';
import { ReactComponent as Disc } from './disc.svg';
import { ReactComponent as UploadCloud } from './upload-cloud.svg';
import { ReactComponent as UserCheck } from './user-check.svg';
import { ReactComponent as UserMinus } from './user-minus.svg';
import { ReactComponent as UserPlus } from './user-plus.svg';
import { ReactComponent as UserX } from './user-x.svg';
import { ReactComponent as Link2 } from './link-2.svg';
import { ReactComponent as GitBranch } from './git-branch.svg';
import { ReactComponent as GitMerge } from './git-merge.svg';
import { ReactComponent as GitPullRequest } from './git-pull-request.svg';
import { ReactComponent as FileMinus } from './file-minus.svg';
import { ReactComponent as FilePlus } from './file-plus.svg';
import { ReactComponent as FileText } from './file-text.svg';
import { ReactComponent as FolderMinus } from './folder-minus.svg';
import { ReactComponent as FolderPlus } from './folder-plus.svg';
import { ReactComponent as DivideCircle } from './divide-circle.svg';
import { ReactComponent as DivideSquare } from './divide-square.svg';
import { ReactComponent as DollarSign } from './dollar-sign.svg';
import { ReactComponent as DownloadCloud } from './download-cloud.svg';
import { ReactComponent as Share2 } from './share-2.svg';
import { ReactComponent as ShieldOff } from './shield-off.svg';
import { ReactComponent as Divide } from './divide.svg';
import { ReactComponent as Download } from './download.svg';
import { ReactComponent as Dribbble } from './dribbble.svg';
import { ReactComponent as Droplet } from './droplet.svg';
import { ReactComponent as Save } from './save.svg';
import { ReactComponent as Scissors } from './scissors.svg';
import { ReactComponent as Search } from './search.svg';
import { ReactComponent as Send } from './send.svg';
import { ReactComponent as Server } from './server.svg';
import { ReactComponent as Settings } from './settings.svg';
import { ReactComponent as Share } from './share.svg';
import { ReactComponent as Shield } from './shield.svg';
import { ReactComponent as ShoppingBag } from './shopping-bag.svg';
import { ReactComponent as ShoppingCart } from './shopping-cart.svg';
import { ReactComponent as Shuffle } from './shuffle.svg';
import { ReactComponent as Sidebar } from './sidebar.svg';
import { ReactComponent as SkipBack } from './skip-back.svg';
import { ReactComponent as SkipForward } from './skip-forward.svg';
import { ReactComponent as Slack } from './slack.svg';
import { ReactComponent as Slash } from './slash.svg';
import { ReactComponent as Sliders } from './sliders.svg';
import { ReactComponent as Smartphone } from './smartphone.svg';
import { ReactComponent as Smile } from './smile.svg';
import { ReactComponent as Speaker } from './speaker.svg';
import { ReactComponent as Square } from './square.svg';
import { ReactComponent as Star } from './star.svg';
import { ReactComponent as StopCircle } from './stop-circle.svg';
import { ReactComponent as Sun } from './sun.svg';
import { ReactComponent as Sunrise } from './sunrise.svg';
import { ReactComponent as Sunset } from './sunset.svg';
import { ReactComponent as ZapOff } from './zap-off.svg';
import { ReactComponent as Zap } from './zap.svg';
import { ReactComponent as ZoomIn } from './zoom-in.svg';
import { ReactComponent as ZoomOut } from './zoom-out.svg';
import { ReactComponent as XCircle } from './x-circle.svg';
import { ReactComponent as XOctagon } from './x-octagon.svg';
import { ReactComponent as XSquare } from './x-square.svg';
import { ReactComponent as X } from './x.svg';
import { ReactComponent as VideoOff } from './video-off.svg';
import { ReactComponent as Video } from './video.svg';
import { ReactComponent as Voicemail } from './voicemail.svg';
import { ReactComponent as Volume1 } from './volume-1.svg';
import { ReactComponent as Volume2 } from './volume-2.svg';
import { ReactComponent as VolumeX } from './volume-x.svg';
import { ReactComponent as Navigation2 } from './navigation-2.svg';
import { ReactComponent as Navigation } from './navigation.svg';
import { ReactComponent as Mail } from './mail.svg';
import { ReactComponent as MapPin } from './map-pin.svg';
import { ReactComponent as Map } from './map.svg';
import { ReactComponent as Maximize2 } from './maximize-2.svg';
import { ReactComponent as Maximize } from './maximize.svg';
import { ReactComponent as Meh } from './meh.svg';
import { ReactComponent as Menu } from './menu.svg';
import { ReactComponent as MessageCircle } from './message-circle.svg';
import { ReactComponent as MessageSquare } from './message-square.svg';
import { ReactComponent as MicOff } from './mic-off.svg';
import { ReactComponent as Mic } from './mic.svg';
import { ReactComponent as Minimize2 } from './minimize-2.svg';
import { ReactComponent as Minimize } from './minimize.svg';
import { ReactComponent as MinusCircle } from './minus-circle.svg';
import { ReactComponent as MinusSquare } from './minus-square.svg';
import { ReactComponent as Minus } from './minus.svg';
import { ReactComponent as Monitor } from './monitor.svg';
import { ReactComponent as Moon } from './moon.svg';
import { ReactComponent as MoreHorizontal } from './more-horizontal.svg';
import { ReactComponent as MoreVertical } from './more-vertical.svg';
import { ReactComponent as MousePointer } from './mouse-pointer.svg';
import { ReactComponent as Move } from './move.svg';
import { ReactComponent as Music } from './music.svg';
import { ReactComponent as PackageXVG } from './package.svg';
import { ReactComponent as Paperclip } from './paperclip.svg';
import { ReactComponent as PauseCircle } from './pause-circle.svg';
import { ReactComponent as Pause } from './pause.svg';
import { ReactComponent as PenTool } from './pen-tool.svg';
import { ReactComponent as Percent } from './percent.svg';
import { ReactComponent as PhoneCall } from './phone-call.svg';
import { ReactComponent as PhoneIncoming } from './phone-incoming.svg';
import { ReactComponent as PhoneForwarded } from './phone-forwarded.svg';
import { ReactComponent as PhoneMissed } from './phone-missed.svg';
import { ReactComponent as PhoneOff } from './phone-off.svg';
import { ReactComponent as PhoneOutgoing } from './phone-outgoing.svg';
import { ReactComponent as Phone } from './phone.svg';
import { ReactComponent as PieChart } from './pie-chart.svg';
import { ReactComponent as PlayCircle } from './play-circle.svg';
import { ReactComponent as Play } from './play.svg';
import { ReactComponent as PlusCircle } from './plus-circle.svg';
import { ReactComponent as PlusSquare } from './plus-square.svg';
import { ReactComponent as Plus } from './plus.svg';
import { ReactComponent as Pocket } from './pocket.svg';
import { ReactComponent as Power } from './power.svg';
import { ReactComponent as Printer } from './printer.svg';
import { ReactComponent as ExternalLink } from './external-link.svg';

export const ActivityIcon = Activity;
export const AirplayIcon = Airplay;
export const AlertCircleIcon = AlertCircle;
export const AlertOctagonIcon = AlertOctagon;
export const AlertTriangleIcon = AlertTriangle;
export const AlignCenterIcon = AlignCenter;
export const AlignJustifyIcon = AlignJustify;
export const AlignLeftIcon = AlignLeft;
export const AlignRightIcon = AlignRight;
export const AnchorIcon = Anchor;
export const ApertureIcon = Aperture;
export const ArchiveIcon = Archive;
export const ArrowIcon = Arrow;
export const ArrowDownLeftIcon = ArrowDownLeft;
export const ArrowDownRightIcon = ArrowDownRight;
export const ArrowDownIcon = ArrowDown;
export const ArrowLeftCircleIcon = ArrowLeftCircle;
export const ArrowLeftIcon = ArrowLeft;
export const ArrowRightCircleIcon = ArrowRightCircle;
export const ArrowRightIcon = ArrowRight;
export const ArrowUpCircleIcon = ArrowUpCircle;
export const ArrowUpIcon = ArrowUp;
export const ArrowUpLeftIcon = ArrowUpLeft;
export const ArrowUpRightIcon = ArrowUpRight;
export const AtIcon = At;
export const AwardIcon = Award;
export const BarCharIcon = BarChar;
export const BarIcon = Bar;
export const BatteryIcon = Battery;
export const BatteryChargingIcon = BatteryCharging;
export const BellOffIcon = BellOff;
export const BellIcon = Bell;
export const BluetoothIcon = Bluetooth;
export const BoldIcon = Bold;
export const BookOpenIcon = BookOpen;
export const BookIcon = Book;
export const BookmarkIcon = Bookmark;
export const BoxIcon = Box;
export const BriefcaseIcon = Briefcase;
export const CalendarIcon = Calendar;
export const CameraOffIcon = CameraOff;
export const CameraIcon = Camera;
export const CastIcon = Cast;
export const CheckCircleIcon = CheckCircle;
export const CheckSquareIcon = CheckSquare;
export const CheckIcon = Check;
export const ChevronDownIcon = ChevronDown;
export const ChevronLeftIcon = ChevronLeft;
export const ChevronRightIcon = ChevronRight;
export const ChevronUpIcon = ChevronUp;
export const ChromeIcon = Chrome;
export const ChevronsDownIcon = ChevronsDown;
export const ChevronsLeftIcon = ChevronsLeft;
export const ChevronsRightIcon = ChevronsRight;
export const ChevronsUpIcon = ChevronsUp;
export const CircleIcon = Circle;
export const ClipboardIcon = Clipboard;
export const ClockIcon = Clock;
export const CloudDrizzleIcon = CloudDrizzle;
export const CloudLightningIcon = CloudLightning;
export const CloudOffIcon = CloudOff;
export const CloudRainIcon = CloudRain;
export const CloudSnowIcon = CloudSnow;
export const CloudIcon = Cloud;
export const CodeIcon = Code;
export const CodepenIcon = Codepen;
export const CodesandboxIcon = Codesandbox;
export const CoffeeIcon = Coffee;
export const ColumnsIcon = Columns;
export const CommandIcon = Command;
export const CompassIcon = Compass;
export const CopyIcon = Copy;
export const CornerDownLeftIcon = CornerDownLeft;
export const CornerDownRightIcon = CornerDownRight;
export const CornerLeftDownIcon = CornerLeftDown;
export const CornerRightDownIcon = CornerRightDown;
export const CornerLeftUpIcon = CornerLeftUp;
export const CornerRightUpIcon = CornerRightUp;
export const CornerUpLeftIcon = CornerUpLeft;
export const CornerUpRightIcon = CornerUpRight;
export const CpuIcon = Cpu;
export const CreditCardIcon = CreditCard;
export const CropIcon = Crop;
export const CrosshairIcon = Crosshair;
export const DatabaseIcon = Database;
export const DeleteIcon = DeleteSVG;
export const DiscIcon = Disc;
export const DivideIcon = Divide;
export const DollarIcon = Dollar;
export const DownloadIcon = Download;
export const DribbbleIcon = Dribbble;
export const DropletIcon = Droplet;
export const WatchIcon = Watch;
export const WifiOffIcon = WifiOff;
export const WifiIcon = Wifi;
export const WindIcon = Wind;
export const EditIcon = Edit;
export const Edit2Icon = Edit2;
export const Edit3Icon = Edit3;
export const ExternalIcon = External;
export const EyeIcon = Eye;
export const EyeOffIcon = EyeOff;
export const RadioIcon = Radio;
export const ReceiptIcon = Receipt;
export const RefreshCcwIcon = RefreshCcw;
export const RefreshCwIcon = RefreshCw;
export const RepeatIcon = Repeat;
export const RewindIcon = Rewind;
export const RotateCcwIcon = RotateCcw;
export const RotateCwIcon = RotateCw;
export const RssIcon = Rss;
export const TableIcon = Table;
export const TabletIcon = Tablet;
export const TagIcon = Tag;
export const TargetIcon = Target;
export const TerminalIcon = Terminal;
export const ThermometerIcon = Thermometer;
export const ThumbsDownIcon = ThumbsDown;
export const ThumbsUpIcon = ThumbsUp;
export const ToggleLeftIcon = ToggleLeft;
export const ToggleRightIcon = ToggleRight;
export const ToolIcon = Tool;
export const TrashIcon = Trash;
export const Trash2Icon = Trash2;
export const TrelloIcon = Trello;
export const TrendingDownIcon = TrendingDown;
export const TrendingUpIcon = TrendingUp;
export const TriangleIcon = Triangle;
export const TruckIcon = Truck;
export const TvIcon = Tv;
export const TwitchIcon = Twitch;
export const TwitterIcon = Twitter;
export const TypeIcon = TypeSVG;
export const YoutubeIcon = Youtube;
export const UmbrellaIcon = Umbrella;
export const UnderlineIcon = Underline;
export const UnlockIcon = Unlock;
export const UploadIcon = Upload;
export const UserIcon = User;
export const ImageIcon = Image;
export const InboxIcon = Inbox;
export const InfoIcon = Info;
export const InstagramIcon = Instagram;
export const ItalicIcon = Italic;
export const OctagonIcon = Octagon;
export const LayersIcon = Layers;
export const LayoutIcon = Layout;
export const LifeIcon = Life;
export const LinkIcon = Link;
export const LinkedinIcon = Linkedin;
export const ListIcon = List;
export const LoaderIcon = Loader;
export const LockIcon = Lock;
export const LogOutIcon = LogOut;
export const LogInIcon = LogIn;
export const KeyIcon = Key;
export const HardIcon = Hard;
export const HashIcon = Hash;
export const HeartIcon = Heart;
export const HeadphonesIcon = Headphones;
export const HelpIcon = Help;
export const HexagonIcon = Hexagon;
export const HomeIcon = Home;
export const GiftIcon = Gift;
export const GitIcon = Git;
export const GithubIcon = Github;
export const GitlabIcon = Gitlab;
export const GlobeIcon = Globe;
export const GridIcon = Grid;
export const FacebookIcon = Facebook;
export const FastIcon = Fast;
export const FeatherIcon = Feather;
export const FigmaIcon = Figma;
export const FileIcon = File;
export const FilmIcon = Film;
export const FilterIcon = Filter;
export const FlagIcon = Flag;
export const FolderIcon = Folder;
export const FramerIcon = Framer;
export const FrownIcon = Frown;
export const SaveIcon = Save;
export const ScissorsIcon = Scissors;
export const SearchIcon = Search;
export const SendIcon = Send;
export const ServerIcon = Server;
export const SettingsIcon = Settings;
export const ShareIcon = Share;
export const ShieldIcon = Shield;
export const ShoppingBagIcon = ShoppingBag;
export const ShoppingCartIcon = ShoppingCart;
export const ShuffleIcon = Shuffle;
export const SidebarIcon = Sidebar;
export const SkipBackIcon = SkipBack;
export const SkipForwardIcon = SkipForward;
export const SlackIcon = Slack;
export const SlashIcon = Slash;
export const SlidersIcon = Sliders;
export const SmartphoneIcon = Smartphone;
export const SmileIcon = Smile;
export const SpeakerIcon = Speaker;
export const SquareIcon = Square;
export const StarIcon = Star;
export const StopIcon = StopCircle;
export const SunIcon = Sun;
export const SunriseIcon = Sunrise;
export const SunsetIcon = Sunset;
export const ZapOffIcon = ZapOff;
export const ZapIcon = Zap;
export const ZoomInIcon = ZoomIn;
export const ZoomOutIcon = ZoomOut;
export const XCircleIcon = XCircle;
export const XOctagonIcon = XOctagon;
export const XSquareIcon = XSquare;
export const XIcon = X;
export const VideoOffIcon = VideoOff;
export const VideoIcon = Video;
export const VoicemailIcon = Voicemail;
export const Volume1Icon = Volume1;
export const Volume2Icon = Volume2;
export const VolumeIcon = VolumeX;
export const Navigation2Icon = Navigation2;
export const NavigationIcon = Navigation;
export const MailIcon = Mail;
export const MapPinIcon = MapPin;
export const MapIcon = Map;
export const Maximize2Icon = Maximize2;
export const MaximizeIcon = Maximize;
export const MehIcon = Meh;
export const MenuIcon = Menu;
export const MessageCircleIcon = MessageCircle;
export const MessageSquareIcon = MessageSquare;
export const MicOffIcon = MicOff;
export const MicIcon = Mic;
export const Minimize2Icon = Minimize2;
export const MinimizeIcon = Minimize;
export const MinusIcon = Minus;
export const MinusSquareIcon = MinusSquare;
export const MinusCircleIcon = MinusCircle;
export const MonitorIcon = Monitor;
export const MoonIcon = Moon;
export const MoreVerticalIcon = MoreVertical;
export const MoreHorizontalIcon = MoreHorizontal;
export const MousePointerIcon = MousePointer;
export const MoveIcon = Move;
export const MusicIcon = Music;
export const PackageIcon = PackageXVG;
export const PaperclipIcon = Paperclip;
export const PauseCircleIcon = PauseCircle;
export const PauseIcon = Pause;
export const PenToolIcon = PenTool;
export const PercentIcon = Percent;
export const PhoneCallIcon = PhoneCall;
export const PhoneForwardedIcon = PhoneForwarded;
export const PhoneIncomingIcon = PhoneIncoming;
export const PhoneMissedIcon = PhoneMissed;
export const PhoneOffIcon = PhoneOff;
export const PhoneOutgoingIcon = PhoneOutgoing;
export const PhoneIcon = Phone;
export const PieChartIcon = PieChart;
export const PlayCircleIcon = PlayCircle;
export const PlayIcon = Play;
export const PlusCircleIcon = PlusCircle;
export const PlusSquareIcon = PlusSquare;
export const PlusIcon = Plus;
export const PocketIcon = Pocket;
export const PowerIcon = Power;
export const PrinterIcon = Printer;
export const ExternalLinkIcon = ExternalLink;
export const UploadCloudIcon = UploadCloud;
export const UserCheckIcon = UserCheck;
export const UserMinusIcon = UserMinus;
export const UserPlusIcon = UserPlus;
export const UserXIcon = UserX;
export const Link2Icon = Link2;
export const GitBranchIcon = GitBranch;
export const GitMergeIcon = GitMerge;
export const GitPullRequestIcon = GitPullRequest;
export const FileMinusIcon = FileMinus;
export const FilePlusIcon = FilePlus;
export const FileTextIcon = FileText;
export const FolderMinusIcon = FolderMinus;
export const FolderPlusIcon = FolderPlus;
export const DivideCircleIcon = DivideCircle;
export const DivideSquareIcon = DivideSquare;
export const DollarSignIcon = DollarSign;
export const DownloadCloudIcon = DownloadCloud;
export const Share2Icon = Share2;
export const ShieldOffIcon = ShieldOff;
