import Activity from './activity.svg';
import Airplay from './airplay.svg';
import AlertCircle from './alert-circle.svg';
import AlertOctagon from './alert-octagon.svg';
import AlertTriangle from './alert-triangle.svg';
import AlignCenter from './align-center.svg';
import AlignJustify from './align-justify.svg';
import AlignLeft from './align-left.svg';
import AlignRight from './align-right.svg';
import Anchor from './anchor.svg';
import Aperture from './aperture.svg';
import Archive from './archive.svg';
import Arrow from './arrow-down-circle.svg';
import ArrowDownLeft from './arrow-down-left.svg';
import ArrowDownRight from './arrow-down-right.svg';
import ArrowDown from './arrow-down.svg';
import ArrowLeftCircle from './arrow-left-circle.svg';
import ArrowLeft from './arrow-left.svg';
import ArrowRightCircle from './arrow-right-circle.svg';
import ArrowRight from './arrow-right.svg';
import ArrowUpCircle from './arrow-up-circle.svg';
import ArrowUp from './arrow-up.svg';
import ArrowUpLeft from './arrow-up-left.svg';
import ArrowUpRight from './arrow-up-right.svg';
import At from './at-sign.svg';
import Award from './award.svg';
import BarChar from './bar-chart-2.svg';
import Bar from './bar-chart.svg';
import Battery from './battery.svg';
import BatteryCharging from './battery-charging.svg';
import BellOff from './bell-off.svg';
import Bell from './bell.svg';
import Bluetooth from './bluetooth.svg';
import Bold from './bold.svg';
import BookOpen from './book-open.svg';
import Book from './book.svg';
import Bookmark from './bookmark.svg';
import Box from './box.svg';
import Briefcase from './briefcase.svg';
import Calendar from './calendar.svg';
import CameraOff from './camera-off.svg';
import Camera from './camera.svg';
import Cast from './cast.svg';
import CheckCircle from './check-circle.svg';
import CheckSquare from './check-square.svg';
import Check from './check.svg';
import ChevronDown from './chevron-down.svg';
import ChevronLeft from './chevron-left.svg';
import ChevronRight from './chevron-right.svg';
import ChevronUp from './chevron-up.svg';
import Chrome from './chrome.svg';
import ChevronsDown from './chevrons-down.svg';
import ChevronsLeft from './chevrons-left.svg';
import ChevronsRight from './chevrons-right.svg';
import ChevronsUp from './chevrons-up.svg';
import Circle from './circle.svg';
import Clipboard from './clipboard.svg';
import Clock from './clock.svg';
import CloudDrizzle from './cloud-drizzle.svg';
import CloudLightning from './cloud-lightning.svg';
import CloudOff from './cloud-off.svg';
import CloudRain from './cloud-rain.svg';
import CloudSnow from './cloud-snow.svg';
import Cloud from './cloud.svg';
import Code from './code.svg';
import Codepen from './codepen.svg';
import Codesandbox from './codesandbox.svg';
import Coffee from './coffee.svg';
import Columns from './columns.svg';
import Command from './command.svg';
import Compass from './compass.svg';
import Copy from './copy.svg';
import CornerDownLeft from './corner-down-left.svg';
import CornerDownRight from './corner-down-right.svg';
import CornerLeftDown from './corner-left-down.svg';
import CornerRightDown from './corner-right-down.svg';
import CornerLeftUp from './corner-left-up.svg';
import CornerRightUp from './corner-right-up.svg';
import CornerUpLeft from './corner-up-left.svg';
import CornerUpRight from './corner-up-right.svg';
import Cpu from './cpu.svg';
import CreditCard from './credit-card.svg';
import Crop from './crop.svg';
import Crosshair from './crosshair.svg';
import DeleteSVG from './delete.svg';
import Dollar from './dollar-sign.svg';
import Watch from './watch.svg';
import WifiOff from './wifi-off.svg';
import Wifi from './wifi.svg';
import Wind from './wind.svg';
import Edit2 from './edit-2.svg';
import Edit3 from './edit-3.svg';
import Edit from './edit.svg';
import External from './external-link.svg';
import EyeOff from './eye-off.svg';
import Eye from './eye.svg';
import Radio from './radio.svg';
import Receipt from './receipt-outline 2.svg';
import RefreshCcw from './refresh-ccw.svg';
import RefreshCw from './refresh-cw.svg';
import Repeat from './repeat.svg';
import Rewind from './rewind.svg';
import RotateCcw from './rotate-ccw.svg';
import RotateCw from './rotate-cw.svg';
import Rss from './rss.svg';
import Table from './table.svg';
import Tablet from './tablet.svg';
import Tag from './tag.svg';
import Target from './target.svg';
import Terminal from './terminal.svg';
import Thermometer from './thermometer.svg';
import ThumbsDown from './thumbs-down.svg';
import ThumbsUp from './thumbs-up.svg';
import ToggleLeft from './toggle-left.svg';
import ToggleRight from './toggle-right.svg';
import Tool from './tool.svg';
import Trash2 from './trash-2.svg';
import Trash from './trash.svg';
import Trello from './trello.svg';
import TrendingDown from './trending-down.svg';
import TrendingUp from './trending-up.svg';
import Triangle from './triangle.svg';
import Truck from './truck.svg';
import Tv from './tv.svg';
import Twitch from './twitch.svg';
import Twitter from './twitter.svg';
import TypeSVG from './type.svg';
import Youtube from './youtube.svg';
import Umbrella from './umbrella.svg';
import Underline from './underline.svg';
import Unlock from './unlock.svg';
import Upload from './upload.svg';
import User from './user.svg';
import Image from './image.svg';
import Inbox from './inbox.svg';
import Info from './info.svg';
import Instagram from './instagram.svg';
import Italic from './italic.svg';
import Octagon from './octagon.svg';
import Layers from './layers.svg';
import Layout from './layout.svg';
import Life from './life-buoy.svg';
import Link from './link.svg';
import Linkedin from './linkedin.svg';
import List from './list.svg';
import Loader from './loader.svg';
import Lock from './lock.svg';
import LogIn from './log-in.svg';
import LogOut from './log-out.svg';
import Key from './key.svg';
import Hard from './hard-drive.svg';
import Hash from './hash.svg';
import Heart from './heart.svg';
import Headphones from './headphones.svg';
import Help from './help-circle.svg';
import Hexagon from './hexagon.svg';
import Home from './home.svg';
import Gift from './gift.svg';
import Git from './git-commit.svg';
import Github from './github.svg';
import Gitlab from './gitlab.svg';
import Globe from './globe.svg';
import Grid from './grid.svg';
import Facebook from './facebook.svg';
import Fast from './fast-forward.svg';
import Feather from './feather.svg';
import Figma from './figma.svg';
import File from './file.svg';
import Film from './film.svg';
import Filter from './filter.svg';
import Flag from './flag.svg';
import Folder from './folder.svg';
import Framer from './framer.svg';
import Frown from './frown.svg';
import Database from './database.svg';
import Disc from './disc.svg';
import UploadCloud from './upload-cloud.svg';
import UserCheck from './user-check.svg';
import UserMinus from './user-minus.svg';
import UserPlus from './user-plus.svg';
import UserX from './user-x.svg';
import Link2 from './link-2.svg';
import GitBranch from './git-branch.svg';
import GitMerge from './git-merge.svg';
import GitPullRequest from './git-pull-request.svg';
import FileMinus from './file-minus.svg';
import FilePlus from './file-plus.svg';
import FileText from './file-text.svg';
import FolderMinus from './folder-minus.svg';
import FolderPlus from './folder-plus.svg';
import DivideCircle from './divide-circle.svg';
import DivideSquare from './divide-square.svg';
import DollarSign from './dollar-sign.svg';
import DownloadCloud from './download-cloud.svg';
import Share2 from './share-2.svg';
import ShieldOff from './shield-off.svg';
import Divide from './divide.svg';
import Download from './download.svg';
import Dribbble from './dribbble.svg';
import Droplet from './droplet.svg';
import Save from './save.svg';
import Scissors from './scissors.svg';
import Search from './search.svg';
import Send from './send.svg';
import Server from './server.svg';
import Settings from './settings.svg';
import Share from './share.svg';
import Shield from './shield.svg';
import ShoppingBag from './shopping-bag.svg';
import ShoppingCart from './shopping-cart.svg';
import Shuffle from './shuffle.svg';
import Sidebar from './sidebar.svg';
import SkipBack from './skip-back.svg';
import SkipForward from './skip-forward.svg';
import Slack from './slack.svg';
import Slash from './slash.svg';
import Sliders from './sliders.svg';
import Smartphone from './smartphone.svg';
import Smile from './smile.svg';
import Speaker from './speaker.svg';
import Square from './square.svg';
import Star from './star.svg';
import StopCircle from './stop-circle.svg';
import Sun from './sun.svg';
import Sunrise from './sunrise.svg';
import Sunset from './sunset.svg';
import ZapOff from './zap-off.svg';
import Zap from './zap.svg';
import ZoomIn from './zoom-in.svg';
import ZoomOut from './zoom-out.svg';
import XCircle from './x-circle.svg';
import XOctagon from './x-octagon.svg';
import XSquare from './x-square.svg';
import X from './x.svg';
import VideoOff from './video-off.svg';
import Video from './video.svg';
import Voicemail from './voicemail.svg';
import Volume1 from './volume-1.svg';
import Volume2 from './volume-2.svg';
import VolumeX from './volume-x.svg';
import Navigation2 from './navigation-2.svg';
import Navigation from './navigation.svg';
import Mail from './mail.svg';
import MapPin from './map-pin.svg';
import Map from './map.svg';
import Maximize2 from './maximize-2.svg';
import Maximize from './maximize.svg';
import Meh from './meh.svg';
import Menu from './menu.svg';
import MessageCircle from './message-circle.svg';
import MessageSquare from './message-square.svg';
import MicOff from './mic-off.svg';
import Mic from './mic.svg';
import Minimize2 from './minimize-2.svg';
import Minimize from './minimize.svg';
import MinusCircle from './minus-circle.svg';
import MinusSquare from './minus-square.svg';
import Minus from './minus.svg';
import Monitor from './monitor.svg';
import Moon from './moon.svg';
import MoreHorizontal from './more-horizontal.svg';
import MoreVertical from './more-vertical.svg';
import MousePointer from './mouse-pointer.svg';
import Move from './move.svg';
import Music from './music.svg';
import PackageXVG from './package.svg';
import Paperclip from './paperclip.svg';
import PauseCircle from './pause-circle.svg';
import Pause from './pause.svg';
import PenTool from './pen-tool.svg';
import Percent from './percent.svg';
import PhoneCall from './phone-call.svg';
import PhoneIncoming from './phone-incoming.svg';
import PhoneForwarded from './phone-forwarded.svg';
import PhoneMissed from './phone-missed.svg';
import PhoneOff from './phone-off.svg';
import PhoneOutgoing from './phone-outgoing.svg';
import Phone from './phone.svg';
import PieChart from './pie-chart.svg';
import PlayCircle from './play-circle.svg';
import Play from './play.svg';
import PlusCircle from './plus-circle.svg';
import PlusSquare from './plus-square.svg';
import Plus from './plus.svg';
import Pocket from './pocket.svg';
import Power from './power.svg';
import Printer from './printer.svg';
import ExternalLink from './external-link.svg';

export const ActivityIcon = Activity;
export const AirplayIcon = Airplay;
export const AlertCircleIcon = AlertCircle;
export const AlertOctagonIcon = AlertOctagon;
export const AlertTriangleIcon = AlertTriangle;
export const AlignCenterIcon = AlignCenter;
export const AlignJustifyIcon = AlignJustify;
export const AlignLeftIcon = AlignLeft;
export const AlignRightIcon = AlignRight;
export const AnchorIcon = Anchor;
export const ApertureIcon = Aperture;
export const ArchiveIcon = Archive;
export const ArrowIcon = Arrow;
export const ArrowDownLeftIcon = ArrowDownLeft;
export const ArrowDownRightIcon = ArrowDownRight;
export const ArrowDownIcon = ArrowDown;
export const ArrowLeftCircleIcon = ArrowLeftCircle;
export const ArrowLeftIcon = ArrowLeft;
export const ArrowRightCircleIcon = ArrowRightCircle;
export const ArrowRightIcon = ArrowRight;
export const ArrowUpCircleIcon = ArrowUpCircle;
export const ArrowUpIcon = ArrowUp;
export const ArrowUpLeftIcon = ArrowUpLeft;
export const ArrowUpRightIcon = ArrowUpRight;
export const AtIcon = At;
export const AwardIcon = Award;
export const BarCharIcon = BarChar;
export const BarIcon = Bar;
export const BatteryIcon = Battery;
export const BatteryChargingIcon = BatteryCharging;
export const BellOffIcon = BellOff;
export const BellIcon = Bell;
export const BluetoothIcon = Bluetooth;
export const BoldIcon = Bold;
export const BookOpenIcon = BookOpen;
export const BookIcon = Book;
export const BookmarkIcon = Bookmark;
export const BoxIcon = Box;
export const BriefcaseIcon = Briefcase;
export const CalendarIcon = Calendar;
export const CameraOffIcon = CameraOff;
export const CameraIcon = Camera;
export const CastIcon = Cast;
export const CheckCircleIcon = CheckCircle;
export const CheckSquareIcon = CheckSquare;
export const CheckIcon = Check;
export const ChevronDownIcon = ChevronDown;
export const ChevronLeftIcon = ChevronLeft;
export const ChevronRightIcon = ChevronRight;
export const ChevronUpIcon = ChevronUp;
export const ChromeIcon = Chrome;
export const ChevronsDownIcon = ChevronsDown;
export const ChevronsLeftIcon = ChevronsLeft;
export const ChevronsRightIcon = ChevronsRight;
export const ChevronsUpIcon = ChevronsUp;
export const CircleIcon = Circle;
export const ClipboardIcon = Clipboard;
export const ClockIcon = Clock;
export const CloudDrizzleIcon = CloudDrizzle;
export const CloudLightningIcon = CloudLightning;
export const CloudOffIcon = CloudOff;
export const CloudRainIcon = CloudRain;
export const CloudSnowIcon = CloudSnow;
export const CloudIcon = Cloud;
export const CodeIcon = Code;
export const CodepenIcon = Codepen;
export const CodesandboxIcon = Codesandbox;
export const CoffeeIcon = Coffee;
export const ColumnsIcon = Columns;
export const CommandIcon = Command;
export const CompassIcon = Compass;
export const CopyIcon = Copy;
export const CornerDownLeftIcon = CornerDownLeft;
export const CornerDownRightIcon = CornerDownRight;
export const CornerLeftDownIcon = CornerLeftDown;
export const CornerRightDownIcon = CornerRightDown;
export const CornerLeftUpIcon = CornerLeftUp;
export const CornerRightUpIcon = CornerRightUp;
export const CornerUpLeftIcon = CornerUpLeft;
export const CornerUpRightIcon = CornerUpRight;
export const CpuIcon = Cpu;
export const CreditCardIcon = CreditCard;
export const CropIcon = Crop;
export const CrosshairIcon = Crosshair;
export const DatabaseIcon = Database;
export const DeleteIcon = DeleteSVG;
export const DiscIcon = Disc;
export const DivideIcon = Divide;
export const DollarIcon = Dollar;
export const DownloadIcon = Download;
export const DribbbleIcon = Dribbble;
export const DropletIcon = Droplet;
export const WatchIcon = Watch;
export const WifiOffIcon = WifiOff;
export const WifiIcon = Wifi;
export const WindIcon = Wind;
export const EditIcon = Edit;
export const Edit2Icon = Edit2;
export const Edit3Icon = Edit3;
export const ExternalIcon = External;
export const EyeIcon = Eye;
export const EyeOffIcon = EyeOff;
export const RadioIcon = Radio;
export const ReceiptIcon = Receipt;
export const RefreshCcwIcon = RefreshCcw;
export const RefreshCwIcon = RefreshCw;
export const RepeatIcon = Repeat;
export const RewindIcon = Rewind;
export const RotateCcwIcon = RotateCcw;
export const RotateCwIcon = RotateCw;
export const RssIcon = Rss;
export const TableIcon = Table;
export const TabletIcon = Tablet;
export const TagIcon = Tag;
export const TargetIcon = Target;
export const TerminalIcon = Terminal;
export const ThermometerIcon = Thermometer;
export const ThumbsDownIcon = ThumbsDown;
export const ThumbsUpIcon = ThumbsUp;
export const ToggleLeftIcon = ToggleLeft;
export const ToggleRightIcon = ToggleRight;
export const ToolIcon = Tool;
export const TrashIcon = Trash;
export const Trash2Icon = Trash2;
export const TrelloIcon = Trello;
export const TrendingDownIcon = TrendingDown;
export const TrendingUpIcon = TrendingUp;
export const TriangleIcon = Triangle;
export const TruckIcon = Truck;
export const TvIcon = Tv;
export const TwitchIcon = Twitch;
export const TwitterIcon = Twitter;
export const TypeIcon = TypeSVG;
export const YoutubeIcon = Youtube;
export const UmbrellaIcon = Umbrella;
export const UnderlineIcon = Underline;
export const UnlockIcon = Unlock;
export const UploadIcon = Upload;
export const UserIcon = User;
export const ImageIcon = Image;
export const InboxIcon = Inbox;
export const InfoIcon = Info;
export const InstagramIcon = Instagram;
export const ItalicIcon = Italic;
export const OctagonIcon = Octagon;
export const LayersIcon = Layers;
export const LayoutIcon = Layout;
export const LifeIcon = Life;
export const LinkIcon = Link;
export const LinkedinIcon = Linkedin;
export const ListIcon = List;
export const LoaderIcon = Loader;
export const LockIcon = Lock;
export const LogOutIcon = LogOut;
export const LogInIcon = LogIn;
export const KeyIcon = Key;
export const HardIcon = Hard;
export const HashIcon = Hash;
export const HeartIcon = Heart;
export const HeadphonesIcon = Headphones;
export const HelpIcon = Help;
export const HexagonIcon = Hexagon;
export const HomeIcon = Home;
export const GiftIcon = Gift;
export const GitIcon = Git;
export const GithubIcon = Github;
export const GitlabIcon = Gitlab;
export const GlobeIcon = Globe;
export const GridIcon = Grid;
export const FacebookIcon = Facebook;
export const FastIcon = Fast;
export const FeatherIcon = Feather;
export const FigmaIcon = Figma;
export const FileIcon = File;
export const FilmIcon = Film;
export const FilterIcon = Filter;
export const FlagIcon = Flag;
export const FolderIcon = Folder;
export const FramerIcon = Framer;
export const FrownIcon = Frown;
export const SaveIcon = Save;
export const ScissorsIcon = Scissors;
export const SearchIcon = Search;
export const SendIcon = Send;
export const ServerIcon = Server;
export const SettingsIcon = Settings;
export const ShareIcon = Share;
export const ShieldIcon = Shield;
export const ShoppingBagIcon = ShoppingBag;
export const ShoppingCartIcon = ShoppingCart;
export const ShuffleIcon = Shuffle;
export const SidebarIcon = Sidebar;
export const SkipBackIcon = SkipBack;
export const SkipForwardIcon = SkipForward;
export const SlackIcon = Slack;
export const SlashIcon = Slash;
export const SlidersIcon = Sliders;
export const SmartphoneIcon = Smartphone;
export const SmileIcon = Smile;
export const SpeakerIcon = Speaker;
export const SquareIcon = Square;
export const StarIcon = Star;
export const StopIcon = StopCircle;
export const SunIcon = Sun;
export const SunriseIcon = Sunrise;
export const SunsetIcon = Sunset;
export const ZapOffIcon = ZapOff;
export const ZapIcon = Zap;
export const ZoomInIcon = ZoomIn;
export const ZoomOutIcon = ZoomOut;
export const XCircleIcon = XCircle;
export const XOctagonIcon = XOctagon;
export const XSquareIcon = XSquare;
export const XIcon = X;
export const VideoOffIcon = VideoOff;
export const VideoIcon = Video;
export const VoicemailIcon = Voicemail;
export const Volume1Icon = Volume1;
export const Volume2Icon = Volume2;
export const VolumeIcon = VolumeX;
export const Navigation2Icon = Navigation2;
export const NavigationIcon = Navigation;
export const MailIcon = Mail;
export const MapPinIcon = MapPin;
export const MapIcon = Map;
export const Maximize2Icon = Maximize2;
export const MaximizeIcon = Maximize;
export const MehIcon = Meh;
export const MenuIcon = Menu;
export const MessageCircleIcon = MessageCircle;
export const MessageSquareIcon = MessageSquare;
export const MicOffIcon = MicOff;
export const MicIcon = Mic;
export const Minimize2Icon = Minimize2;
export const MinimizeIcon = Minimize;
export const MinusIcon = Minus;
export const MinusSquareIcon = MinusSquare;
export const MinusCircleIcon = MinusCircle;
export const MonitorIcon = Monitor;
export const MoonIcon = Moon;
export const MoreVerticalIcon = MoreVertical;
export const MoreHorizontalIcon = MoreHorizontal;
export const MousePointerIcon = MousePointer;
export const MoveIcon = Move;
export const MusicIcon = Music;
export const PackageIcon = PackageXVG;
export const PaperclipIcon = Paperclip;
export const PauseCircleIcon = PauseCircle;
export const PauseIcon = Pause;
export const PenToolIcon = PenTool;
export const PercentIcon = Percent;
export const PhoneCallIcon = PhoneCall;
export const PhoneForwardedIcon = PhoneForwarded;
export const PhoneIncomingIcon = PhoneIncoming;
export const PhoneMissedIcon = PhoneMissed;
export const PhoneOffIcon = PhoneOff;
export const PhoneOutgoingIcon = PhoneOutgoing;
export const PhoneIcon = Phone;
export const PieChartIcon = PieChart;
export const PlayCircleIcon = PlayCircle;
export const PlayIcon = Play;
export const PlusCircleIcon = PlusCircle;
export const PlusSquareIcon = PlusSquare;
export const PlusIcon = Plus;
export const PocketIcon = Pocket;
export const PowerIcon = Power;
export const PrinterIcon = Printer;
export const ExternalLinkIcon = ExternalLink;
export const UploadCloudIcon = UploadCloud;
export const UserCheckIcon = UserCheck;
export const UserMinusIcon = UserMinus;
export const UserPlusIcon = UserPlus;
export const UserXIcon = UserX;
export const Link2Icon = Link2;
export const GitBranchIcon = GitBranch;
export const GitMergeIcon = GitMerge;
export const GitPullRequestIcon = GitPullRequest;
export const FileMinusIcon = FileMinus;
export const FilePlusIcon = FilePlus;
export const FileTextIcon = FileText;
export const FolderMinusIcon = FolderMinus;
export const FolderPlusIcon = FolderPlus;
export const DivideCircleIcon = DivideCircle;
export const DivideSquareIcon = DivideSquare;
export const DollarSignIcon = DollarSign;
export const DownloadCloudIcon = DownloadCloud;
export const Share2Icon = Share2;
export const ShieldOffIcon = ShieldOff;
